### ISSUE TITLE
ABTestSDK

### ISSUE THREAD

**Issue by yeguizhong** [sensorsdata/abtesting-sdk-ios#2]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/42663129/196685894-6c555e67-658d-4b81-b24d-f0b7391e55e1.png">
如图，SABFileStorePlugin.m. line 56、57 两个方法过期了

**Comment by yeguizhong** [comment]
希望尽快解决，还等着接入呢

**Comment by yaoyue** [comment]
这里只是方法过期，不影响正常使用，您这边可以先接入，后期我们再做 API 迁移哈

**Comment by yeguizhong** [comment]
我的xcode 编译器已经是处于报错状态了。无法进行下一步，或者有地方可以直接消除吗

**Comment by yaoyue** [comment]
您这边哪个客户呢？你这边是 macOS 还是 iOS 的接入 A/B Testing SDK 呢？方便在客户对接群里咨询一下技术顾问同学嘛，可以直接沟通，远程排查呢

**Comment by yeguizhong** [comment]
还有个问题，这个AB一定要和defaultValue一致吗。 如果我们想统计你们内部接口出错率，就比较麻烦
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/42663129/197098904-a0b17cd4-6fd9-4a2c-ac7b-27b4cdab777f.png">

**Comment by yaoyue** [comment]
是的，这里校验试验配置的合法性，需要确保试验值和默认值类型一致。
对于 A/B Testing 试验，目前支持 数值型、布尔值、字符型等多种试验类型，并且为校验使用合法性，需要校验默认值与返回试验类型一致，防止客户处理试验结果和预期不一致，导致的各种问题。

**Comment by yeguizhong** [comment]
如果我想统计你们这个接口的出错率，就会导致很麻烦。每个ABTest上都得写一些奇怪代码，才能满足我统计接口出错率的需求。 一般使用你们的ABTest，我们会再次封装一次，值校验的问题，我们会处理的。 如果传默认值给SDK，SDK接口无论失败成功都会有值

**Comment by yeguizhong** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/42663129/197136846-0adb674f-c73c-4436-a1c3-14366a3bc0f4.png">
对于这种情况，想要达到埋点效果，就得外边每个abtest调用处去传一个“无用的defaultValue”进来，等返回出去的时候他们再根据返回值判断接口是否成功，进而进行埋点，而无法统一在内部处理埋点逻辑

**Comment by yaoyue** [comment]
您好，这个 defaultValue 时有用且必要的，为了保证业务的稳定。如果 parameName 匹配失败或者没有对应试验，业务层就需要使用 defaultValue 处理。
